update 2024-01-30 14:07:27

diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-backup b/luci-app-amlogic/root/usr/sbin/openwrt-backup
--- a/luci-app-amlogic/root/usr/sbin/openwrt-backup
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-backup
@@ -16,7 +16,7 @@ backup_list_conf="/etc/amlogic_backup_list.conf"
 if [[ -s "${backup_list_conf}" ]]; then
     while IFS= read -r line; do
         BACKUP_LIST+="${line} "
-    done < "${backup_list_conf}"
+    done <"${backup_list_conf}"
 else
     BACKUP_LIST='./etc/AdGuardHome.yaml \
 ./etc/amlogic_backup_list.conf \
@@ -118,9 +118,12 @@ backup() {
 restore() {
     # Find the partition where root is located
     ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-    if [ "${ROOT_PTNAME}" == "" ]; then
-        echo "Cannot find the partition corresponding to the root file system!"
-        exit 1
+    if [[ -z "${ROOT_PTNAME}" ]]; then
+        ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
+        if [[ -z "${ROOT_PTNAME}" ]]; then
+            echo "Cannot find the partition corresponding to the root file system!"
+            exit 1
+        fi
     fi
 
     # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
@@ -164,9 +167,12 @@ restore() {
 gen_fstab() {
     # Find the partition where root is located
     ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-    if [ "${ROOT_PTNAME}" == "" ]; then
-        echo "Cannot find the partition corresponding to the root file system!"
-        exit 1
+    if [[ -z "${ROOT_PTNAME}" ]]; then
+        ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
+        if [[ -z "${ROOT_PTNAME}" ]]; then
+            echo "Cannot find the partition corresponding to the root file system!"
+            exit 1
+        fi
     fi
 
     # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
@@ -186,9 +192,12 @@ gen_fstab() {
     esac
 
     ROOT_MSG=$(lsblk -l -o NAME,PATH,MOUNTPOINT,UUID,FSTYPE,LABEL | awk '$3 ~ /^\/$/ {print $0}')
-    if [ "$ROOT_MSG" == "" ]; then
-        echo "Get rootfs message failed!"
-        exit 1
+    if [[ -z "${ROOT_MSG}" ]]; then
+        ROOT_MSG=$(lsblk -l -o NAME,PATH,MOUNTPOINT,UUID,FSTYPE,LABEL | awk '$3 ~ /^\/overlay$/ {print $0}')
+        if [[ -z "${ROOT_MSG}" ]]; then
+            echo "Get rootfs message failed!"
+            exit 1
+        fi
     fi
 
     ROOT_NAME=$(echo $ROOT_MSG | awk '{print $1}')
@@ -380,10 +389,13 @@ delete_snapshot() {
 
 migrate_snapshot() {
     cur_rootdev=$(lsblk -l -o NAME,MOUNTPOINT | awk '$2~/^\/$/ {print $1}')
-    if [ "${cur_rootdev}" == "" ]; then
-        echo "The disk device corresponding to the current rootfs cannot be found!"
-        read -p "Press [ enter ] to return." q
-        return
+    if [[ -z "${cur_rootdev}" ]]; then
+        cur_rootdev=$(lsblk -l -o NAME,MOUNTPOINT | awk '$2~/^\/overlay$/ {print $1}')
+        if [[ -z "${cur_rootdev}" ]]; then
+            echo "The disk device corresponding to the current rootfs cannot be found!"
+            read -p "Press [ enter ] to return." q
+            return
+        fi
     fi
     dev_pre=$(echo "${cur_rootdev}" | awk '{print substr($1, 1, length($1)-1);}')
     rootdev_idx=$(echo "${cur_rootdev}" | awk '{print substr($1, length($1),1);}')
diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-update-allwinner b/luci-app-amlogic/root/usr/sbin/openwrt-update-allwinner
--- a/luci-app-amlogic/root/usr/sbin/openwrt-update-allwinner
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-update-allwinner
@@ -50,9 +50,12 @@ fi
 
 # Find the partition where root is located
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [ "${ROOT_PTNAME}" == "" ]; then
-    echo "Cannot find the partition corresponding to the root file system!"
-    exit 1
+if [[ -z "${ROOT_PTNAME}" ]]; then
+    ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
+    if [[ -z "${ROOT_PTNAME}" ]]; then
+        echo "Cannot find the partition corresponding to the root file system!"
+        exit 1
+    fi
 fi
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
@@ -142,16 +145,19 @@ n* | N*)
     ;;
 esac
 
-BOOT_NAME=$(echo $BOOT_PART_MSG | awk '{print $1}')
-BOOT_PATH=$(echo $BOOT_PART_MSG | awk '{print $2}')
-BOOT_UUID=$(echo $BOOT_PART_MSG | awk '{print $4}')
+BOOT_NAME=$(echo ${BOOT_PART_MSG} | awk '{print $1}')
+BOOT_PATH=$(echo ${BOOT_PART_MSG} | awk '{print $2}')
+BOOT_UUID=$(echo ${BOOT_PART_MSG} | awk '{print $4}')
 
 # find root partition
 ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/$/ {print $0}')
-ROOT_NAME=$(echo $ROOT_PART_MSG | awk '{print $1}')
-ROOT_PATH=$(echo $ROOT_PART_MSG | awk '{print $2}')
-ROOT_UUID=$(echo $ROOT_PART_MSG | awk '{print $4}')
-case $ROOT_NAME in
+if [[ -z "${ROOT_PART_MSG}" ]]; then
+    ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/overlay$/ {print $0}')
+fi
+ROOT_NAME=$(echo ${ROOT_PART_MSG} | awk '{print $1}')
+ROOT_PATH=$(echo ${ROOT_PART_MSG} | awk '{print $2}')
+ROOT_UUID=$(echo ${ROOT_PART_MSG} | awk '{print $4}')
+case ${ROOT_NAME} in
 ${EMMC_NAME}${PARTITION_NAME}2)
     NEW_ROOT_NAME="${EMMC_NAME}${PARTITION_NAME}3"
     NEW_ROOT_LABEL="${LB_PRE}ROOTFS2"
diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-update-kvm b/luci-app-amlogic/root/usr/sbin/openwrt-update-kvm
--- a/luci-app-amlogic/root/usr/sbin/openwrt-update-kvm
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-update-kvm
@@ -49,9 +49,12 @@ fi
 # Find the partition where root is located
 # vda2 or vda3
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [ "${ROOT_PTNAME}" == "" ]; then
-    echo "Cannot find the partition corresponding to the root file system!"
-    exit 1
+if [[ -z "${ROOT_PTNAME}" ]]; then
+    ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
+    if [[ -z "${ROOT_PTNAME}" ]]; then
+        echo "Cannot find the partition corresponding to the root file system!"
+        exit 1
+    fi
 fi
 
 # Find the disk where the partition is located, only supports sd?? hd?? vd??
@@ -166,11 +169,14 @@ fi
 
 # find root partition
 ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/$/ {print $0}')
-ROOT_NAME=$(echo $ROOT_PART_MSG | awk '{print $1}')
-ROOT_DEV=$(echo $ROOT_PART_MSG | awk '{print $2}')
-ROOT_UUID=$(echo $ROOT_PART_MSG | awk '{print $4}')
+if [[ -z "${ROOT_PART_MSG}" ]]; then
+    ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/overlay$/ {print $0}')
+fi
+ROOT_NAME=$(echo ${ROOT_PART_MSG} | awk '{print $1}')
+ROOT_DEV=$(echo ${ROOT_PART_MSG} | awk '{print $2}')
+ROOT_UUID=$(echo ${ROOT_PART_MSG} | awk '{print $4}')
 
-case $ROOT_NAME in
+case ${ROOT_NAME} in
 ${DISK_NAME}${PART_PRESTR}2)
     NEW_ROOT_NAME="${DISK_NAME}${PART_PRESTR}3"
     NEW_ROOT_LABEL="${LABEL_PRESTR}ROOTFS2"
diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-update-rockchip b/luci-app-amlogic/root/usr/sbin/openwrt-update-rockchip
--- a/luci-app-amlogic/root/usr/sbin/openwrt-update-rockchip
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-update-rockchip
@@ -216,9 +216,12 @@ sleep 3
 
 # Find the partition where root is located
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [ "${ROOT_PTNAME}" == "" ]; then
-    echo "Cannot find the partition corresponding to the root file system!"
-    exit 1
+if [[ -z "${ROOT_PTNAME}" ]]; then
+    ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
+    if [[ -z "${ROOT_PTNAME}" ]]; then
+        echo "Cannot find the partition corresponding to the root file system!"
+        exit 1
+    fi
 fi
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
@@ -319,6 +322,9 @@ BOOT_UUID=$(echo ${BOOT_PART_MSG} | awk '{print $4}')
 
 # find root partition
 ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/$/ {print $0}')
+if [[ -z "${ROOT_PART_MSG}" ]]; then
+    ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/overlay$/ {print $0}')
+fi
 ROOT_NAME=$(echo ${ROOT_PART_MSG} | awk '{print $1}')
 ROOT_PATH=$(echo ${ROOT_PART_MSG} | awk '{print $2}')
 ROOT_UUID=$(echo ${ROOT_PART_MSG} | awk '{print $4}')
