update 2024-07-09 20:11:52

diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-backup b/luci-app-amlogic/root/usr/sbin/openwrt-backup
--- a/luci-app-amlogic/root/usr/sbin/openwrt-backup
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-backup
@@ -30,6 +30,8 @@ else
 ./etc/ksmbd/ksmbdpwd.db \
 ./etc/config/ \
 ./etc/crontabs/ \
+./etc/dae/ \
+./etc/daed/ \
 ./usr/share/openclash/core/ \
 ./etc/openclash/backup/ \
 ./etc/openclash/config/ \
@@ -83,6 +85,11 @@ else
 ./root/.ssh/'
 fi
 
+error_msg() {
+    echo -e " [ERROR] ${1}"
+    exit 1
+}
+
 if dmesg | grep 'meson' >/dev/null 2>&1; then
     PLATFORM="amlogic"
 elif dmesg | grep 'rockchip' >/dev/null 2>&1; then
@@ -91,14 +98,38 @@ elif dmesg | grep 'sun50i-h6' >/dev/null 2>&1; then
     PLATFORM="allwinner"
 else
     source /etc/flippy-openwrt-release
-    case $PLATFORM in
+    case ${PLATFORM} in
     amlogic | rockchip | allwinner | qemu-aarch64) : ;;
-    *)
-        echo "Unknown platform, only support amlogic or rockchip or allwinner h6 or qemu-aarch64!"
-        exit 1
-        ;;
+    *) error_msg "Unknown platform, only support amlogic or rockchip or allwinner h6 or qemu-aarch64!" ;;
     esac
 fi
+
+get_root_partition_name() {
+    local paths=("/" "/overlay" "/rom")
+    local partition_name
+
+    for path in "${paths[@]}"; do
+        partition_name=$(df "${path}" | awk 'NR==2 {print $1}' | awk -F '/' '{print $3}')
+        [[ -n "${partition_name}" ]] && break
+    done
+
+    [[ -z "${partition_name}" ]] && error_msg "Cannot find the root partition!"
+    echo "${partition_name}"
+}
+
+# Get the partition message of the root file system
+get_root_partition_msg() {
+    local paths=("/" "/overlay" "/rom")
+    local partition_name
+
+    for path in "${paths[@]}"; do
+        partition_msg=$(lsblk -l -o NAME,PATH,MOUNTPOINT,UUID,FSTYPE,LABEL | awk '$3 ~ "^" "'"${path}"'" "$" {print $0}')
+        [[ -n "${partition_msg}" ]] && break
+    done
+
+    [[ -z "${partition_msg}" ]] && error_msg "Cannot find the root partition message!"
+    echo "${partition_msg}"
+}
 
 backup() {
     cd /
@@ -110,21 +141,13 @@ backup() {
         echo "Has been backed up to [ ${BACKUP_FILE} ], please download and save."
         exit 0
     else
-        echo "Backup failed!"
-        exit 1
+        error_msg "Backup failed!"
     fi
 }
 
 restore() {
     # Find the partition where root is located
-    ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-    if [[ -z "${ROOT_PTNAME}" ]]; then
-        ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
-        if [[ -z "${ROOT_PTNAME}" ]]; then
-            echo "Cannot find the partition corresponding to the root file system!"
-            exit 1
-        fi
-    fi
+    ROOT_PTNAME="$(get_root_partition_name)"
 
     # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
     case ${ROOT_PTNAME} in
@@ -139,8 +162,7 @@ restore() {
         LB_PRE=""
         ;;
     *)
-        echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-        exit 1
+        error_msg "Unable to recognize the disk type of ${ROOT_PTNAME}!"
         ;;
     esac
 
@@ -159,21 +181,13 @@ restore() {
         reboot
         exit 0
     else
-        echo "The backup file [ ${BACKUP_FILE} ] not found!"
-        exit 1
+        error_msg "The backup file [ ${BACKUP_FILE} ] not found!"
     fi
 }
 
 gen_fstab() {
     # Find the partition where root is located
-    ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-    if [[ -z "${ROOT_PTNAME}" ]]; then
-        ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
-        if [[ -z "${ROOT_PTNAME}" ]]; then
-            echo "Cannot find the partition corresponding to the root file system!"
-            exit 1
-        fi
-    fi
+    ROOT_PTNAME="$(get_root_partition_name)"
 
     # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
     case ${ROOT_PTNAME} in
@@ -186,20 +200,11 @@ gen_fstab() {
         PARTITION_NAME=""
         ;;
     *)
-        echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-        exit 1
+        error_msg "Unable to recognize the disk type of ${ROOT_PTNAME}!"
         ;;
     esac
 
-    ROOT_MSG=$(lsblk -l -o NAME,PATH,MOUNTPOINT,UUID,FSTYPE,LABEL | awk '$3 ~ /^\/$/ {print $0}')
-    if [[ -z "${ROOT_MSG}" ]]; then
-        ROOT_MSG=$(lsblk -l -o NAME,PATH,MOUNTPOINT,UUID,FSTYPE,LABEL | awk '$3 ~ /^\/overlay$/ {print $0}')
-        if [[ -z "${ROOT_MSG}" ]]; then
-            echo "Get rootfs message failed!"
-            exit 1
-        fi
-    fi
-
+    ROOT_MSG="$(get_root_partition_msg)"
     ROOT_NAME=$(echo $ROOT_MSG | awk '{print $1}')
     ROOT_DEV=$(echo $ROOT_MSG | awk '{print $2}')
     ROOT_UUID=$(echo $ROOT_MSG | awk '{print $4}')
@@ -223,7 +228,7 @@ config global
 	option check_fs '0'
 
 config mount
-	option target '/overlay'
+	option target '/rom'
 	option uuid '${ROOT_UUID}'
 	option enabled '1'
 	option enabled_fsck '1'
@@ -388,15 +393,8 @@ delete_snapshot() {
 }
 
 migrate_snapshot() {
-    cur_rootdev=$(lsblk -l -o NAME,MOUNTPOINT | awk '$2~/^\/$/ {print $1}')
-    if [[ -z "${cur_rootdev}" ]]; then
-        cur_rootdev=$(lsblk -l -o NAME,MOUNTPOINT | awk '$2~/^\/overlay$/ {print $1}')
-        if [[ -z "${cur_rootdev}" ]]; then
-            echo "The disk device corresponding to the current rootfs cannot be found!"
-            read -p "Press [ enter ] to return." q
-            return
-        fi
-    fi
+    cur_rootdev="$(get_root_partition_name)"
+
     dev_pre=$(echo "${cur_rootdev}" | awk '{print substr($1, 1, length($1)-1);}')
     rootdev_idx=$(echo "${cur_rootdev}" | awk '{print substr($1, length($1),1);}')
     case $rootdev_idx in
diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic b/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic
--- a/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic
@@ -4,7 +4,7 @@
 # Copyright (C) 2020-- https://github.com/unifreq/openwrt_packit
 # Copyright (C) 2021-- https://github.com/ophub/luci-app-amlogic
 #======================================================================================
-
+#
 # The script supports directly setting parameters for installation, skipping interactive selection
 # openwrt-install-amlogic ${AUTO_MAINLINE_UBOOT} ${ID} ${FDTFILE}:${SOC}:${UBOOT_OVERLOAD} ${SHARED_FSTYPE}
 # E.g: openwrt-install-amlogic yes 11 auto ext4
@@ -14,6 +14,28 @@
 
 # You can also execute the script directly, and interactively select related functions
 # E.g: openwrt-install-amlogic
+#
+#======================================================================================
+
+# Encountered a serious error, abort the script execution
+error_msg() {
+    echo -e "[ERROR] ${1}"
+    exit 1
+}
+
+# Get the partition name of the root file system
+get_root_partition_name() {
+    local paths=("/" "/overlay" "/rom")
+    local partition_name
+
+    for path in "${paths[@]}"; do
+        partition_name=$(df "${path}" | awk 'NR==2 {print $1}' | awk -F '/' '{print $3}')
+        [[ -n "${partition_name}" ]] && break
+    done
+
+    [[ -z "${partition_name}" ]] && error_msg "Cannot find the root partition!"
+    echo "${partition_name}"
+}
 
 # Receive one-key command related parameters
 AUTO_MAINLINE_UBOOT="${1}"
@@ -35,8 +57,7 @@ SPECIFY_UBOOT=""
             SPECIFY_SOC="$(echo "${3}" | awk -F ':' '{print $2}')"
             SPECIFY_UBOOT="$(echo "${3}" | awk -F ':' '{print $3}')"
         else
-            echo "Please enter the DTB file name!"
-            exit 1
+            error_msg "Please enter the DTB file name!"
         fi
     fi
 }
@@ -53,30 +74,23 @@ echo "SHARED_FSTYPE: ${SHARED_FSTYPE}"
 # Current device model
 MYDEVICE_NAME=$(cat /proc/device-tree/model | tr -d '\000')
 if [[ -z "${MYDEVICE_NAME}" ]]; then
-    echo "The device name is empty and cannot be recognized."
-    exit 1
+    error_msg "The device name is empty and cannot be recognized."
 elif [[ ! -f "${op_release}" ]]; then
-    echo "The [ ${op_release} ] file is missing."
-    exit 1
+    error_msg "The [ ${op_release} ] file is missing."
 else
     echo -e "Current device: ${MYDEVICE_NAME} [ amlogic ]"
     sleep 3
 fi
 
 # Find the device name of /
-root_devname=$(df / | tail -n1 | awk '{print $1}' | awk -F '\/' '{print substr($3, 1, length($3)-2)}')
-if [[ -z "${root_devname}" ]]; then
-    root_devname="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '\/' '{print substr($3, 1, length($3)-2)}')"
-fi
+root_devname="$(get_root_partition_name)"
 if lsblk -l | grep -E "^${root_devname}boot0" >/dev/null; then
-    echo "you are running in emmc mode, please boot system with usb or tf card!"
-    exit 1
+    error_msg "you are running in emmc mode, please boot system with usb or tf card!"
 fi
 
 install_emmc="$(lsblk -l -o NAME | grep -oE '(mmcblk[0-9]?boot0)' | sed "s/boot0//g")"
 if [[ "${install_emmc}" == "" ]]; then
-    echo "No emmc can be found to install the openwrt system!"
-    exit 1
+    error_msg "No emmc can be found to install the openwrt system!"
 fi
 
 # EMMC DEVICE NAME
@@ -110,8 +124,7 @@ echo "BOOT: ${BOOT_NAME}"
 if [[ -f "/etc/model_database.txt" ]]; then
     model_database="$(cat /etc/model_database.txt)"
 else
-    echo "[ /etc/model_database.txt ] file is missing."
-    exit 1
+    error_msg "[ /etc/model_database.txt ] file is missing."
 fi
 
 function display_database() {
@@ -164,8 +177,7 @@ elif [[ "${boxtype}" -eq "0" ]]; then
 else
     ret="$(search_model ${boxtype})"
     if [[ -z "${ret}" ]]; then
-        echo "Input error, exit!"
-        exit 1
+        error_msg "Input error, exit!"
     fi
     # 3.  soc
     # 4.  FDTFILE
@@ -180,8 +192,7 @@ else
 fi
 
 if [[ -z "${FDTFILE}" || ! -f "/boot/dtb/amlogic/${FDTFILE}" ]]; then
-    echo "/boot/dtb/amlogic/${FDTFILE} does not exist!"
-    exit 1
+    error_msg "/boot/dtb/amlogic/${FDTFILE} does not exist!"
 fi
 
 echo "AMLOGIC_SOC Value [ ${AMLOGIC_SOC} ]"
@@ -243,8 +254,7 @@ for mnt in $MOUNTS; do
         echo "umount -f $mnt"
         umount -f $mnt
         if [ $? -ne 0 ]; then
-            echo "$mnt Cannot be uninstalled, the installation process is aborted."
-            exit 1
+            error_msg "$mnt Cannot be uninstalled, the installation process is aborted."
         fi
     fi
 done
@@ -485,8 +495,7 @@ while [ $i -le $max_try ]; do
             echo "Not mounted successfully, try again ..."
             i=$((i + 1))
         else
-            echo "Cannot mount the boot file system, give up!"
-            exit 1
+            error_msg "Cannot mount the boot file system, give up!"
         fi
     else
         echo "Successfully mounted."
@@ -538,8 +547,7 @@ while [ $i -le $max_try ]; do
             echo "Not mounted successfully, try again ..."
             i=$((i + 1))
         else
-            echo "Cannot mount rootfs file system, give up!"
-            exit 1
+            error_msg "Cannot mount rootfs file system, give up!"
         fi
     else
         echo "Successfully mounted"
@@ -616,7 +624,7 @@ config  global
         option check_fs '0'
 
 config  mount
-        option target '/overlay'
+        option target '/rom'
         option uuid '${ROOTFS1_UUID}'
         option enabled '1'
         option enabled_fsck '1'
diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-update-allwinner b/luci-app-amlogic/root/usr/sbin/openwrt-update-allwinner
--- a/luci-app-amlogic/root/usr/sbin/openwrt-update-allwinner
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-update-allwinner
@@ -4,7 +4,7 @@
 # Copyright (C) 2020-- https://github.com/unifreq/openwrt_packit
 # Copyright (C) 2021-- https://github.com/ophub/luci-app-amlogic
 #======================================================================================
-
+#
 # The script supports directly setting parameters for update, skipping interactive selection
 # openwrt-update-allwinner ${OPENWRT_FILE} ${AUTO_MAINLINE_UBOOT} ${RESTORE_CONFIG}
 # E.g: openwrt-update-allwinner openwrt_s905d.img.gz yes restore
@@ -12,6 +12,42 @@
 
 # You can also execute the script directly, and interactively select related functions
 # E.g: openwrt-update-allwinner
+#
+#======================================================================================
+
+# Encountered a serious error, abort the script execution
+error_msg() {
+    echo -e "[ERROR] ${1}"
+    exit 1
+}
+
+# Get the partition name of the root file system
+get_root_partition_name() {
+    local paths=("/" "/overlay" "/rom")
+    local partition_name
+
+    for path in "${paths[@]}"; do
+        partition_name=$(df "${path}" | awk 'NR==2 {print $1}' | awk -F '/' '{print $3}')
+        [[ -n "${partition_name}" ]] && break
+    done
+
+    [[ -z "${partition_name}" ]] && error_msg "Cannot find the root partition!"
+    echo "${partition_name}"
+}
+
+# Get the partition message of the root file system
+get_root_partition_msg() {
+    local paths=("/" "/overlay" "/rom")
+    local partition_name
+
+    for path in "${paths[@]}"; do
+        partition_msg=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ "^" "'"${path}"'" "$" {print $0}')
+        [[ -n "${partition_msg}" ]] && break
+    done
+
+    [[ -z "${partition_msg}" ]] && error_msg "Cannot find the root partition message!"
+    echo "${partition_msg}"
+}
 
 # Receive one-key command related parameters
 IMG_NAME=${1}
@@ -30,33 +66,21 @@ elif [[ -f "/etc/flippy-openwrt-release" ]]; then
     MYDTB_FDTFILE="${FDTFILE}"
 fi
 
-[[ -z "${MYDTB_FDTFILE}" ]] && {
-    echo "Invalid FDTFILE: [ ${MYDTB_FDTFILE} ]"
-    exit 1
-}
+[[ -z "${MYDTB_FDTFILE}" ]] && error_msg "Invalid FDTFILE: [ ${MYDTB_FDTFILE} ]"
 
 # Current device model
 MYDEVICE_NAME=$(cat /proc/device-tree/model | tr -d '\000')
 if [[ -z "${MYDEVICE_NAME}" ]]; then
-    echo "The device name is empty and cannot be recognized."
-    exit 1
+    error_msg "The device name is empty and cannot be recognized."
 elif [[ "$(echo ${MYDEVICE_NAME} | grep "V-Plus Cloud")" == "" ]]; then
-    echo "[ ${MYDEVICE_NAME} ] is not [ V-Plus Cloud ] device, please select the correct script."
-    exit 1
+    error_msg "[ ${MYDEVICE_NAME} ] is not [ V-Plus Cloud ] device, please select the correct script."
 else
     echo -e "Current device: ${MYDEVICE_NAME} [ vplus ]"
     sleep 3
 fi
 
 # Find the partition where root is located
-ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [[ -z "${ROOT_PTNAME}" ]]; then
-    ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
-    if [[ -z "${ROOT_PTNAME}" ]]; then
-        echo "Cannot find the partition corresponding to the root file system!"
-        exit 1
-    fi
-fi
+ROOT_PTNAME="$(get_root_partition_name)"
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
 case ${ROOT_PTNAME} in
@@ -71,8 +95,7 @@ mmcblk?p[1-4])
     LB_PRE=""
     ;;
 *)
-    echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-    exit 1
+    error_msg "Unable to recognize the disk type of ${ROOT_PTNAME}!"
     ;;
 esac
 
@@ -117,8 +140,7 @@ sync
 
 # check file
 if [ ! -f "${IMG_NAME}" ]; then
-    echo "No update file found."
-    exit 1
+    error_msg "No update file found."
 else
     echo "Start update from [ ${IMG_NAME} ]"
 fi
@@ -126,8 +148,7 @@ fi
 # find boot partition
 BOOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/boot$/ {print $0}')
 if [ "${BOOT_PART_MSG}" == "" ]; then
-    echo "The boot partition is not exists or not mounted, so it cannot be upgraded with this script!"
-    exit 1
+    error_msg "The boot partition is not exists or not mounted, so it cannot be upgraded with this script!"
 fi
 
 BR_FLAG=1
@@ -150,10 +171,7 @@ BOOT_PATH=$(echo ${BOOT_PART_MSG} | awk '{print $2}')
 BOOT_UUID=$(echo ${BOOT_PART_MSG} | awk '{print $4}')
 
 # find root partition
-ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/$/ {print $0}')
-if [[ -z "${ROOT_PART_MSG}" ]]; then
-    ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/overlay$/ {print $0}')
-fi
+ROOT_PART_MSG="$(get_root_partition_msg)"
 ROOT_NAME=$(echo ${ROOT_PART_MSG} | awk '{print $1}')
 ROOT_PATH=$(echo ${ROOT_PART_MSG} | awk '{print $2}')
 ROOT_UUID=$(echo ${ROOT_PART_MSG} | awk '{print $4}')
@@ -167,16 +185,14 @@ ${EMMC_NAME}${PARTITION_NAME}3)
     NEW_ROOT_LABEL="${LB_PRE}ROOTFS1"
     ;;
 *)
-    echo "The root partition location is invalid, so it cannot be upgraded with this script!"
-    exit 1
+    error_msg "The root partition location is invalid, so it cannot be upgraded with this script!"
     ;;
 esac
 
 # find new root partition
 NEW_ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | grep "${NEW_ROOT_NAME}" | awk '$3 ~ /^part$/ && $5 !~ /^\/$/ && $5 !~ /^\/boot$/ {print $0}')
 if [ "${NEW_ROOT_PART_MSG}" == "" ]; then
-    echo "The new root partition is not exists, so it cannot be upgraded with this script!"
-    exit 1
+    error_msg "The new root partition is not exists, so it cannot be upgraded with this script!"
 fi
 NEW_ROOT_NAME=$(echo $NEW_ROOT_PART_MSG | awk '{print $1}')
 NEW_ROOT_PATH=$(echo $NEW_ROOT_PART_MSG | awk '{print $2}')
@@ -188,12 +204,10 @@ losetup -f -P $IMG_NAME
 if [ $? -eq 0 ]; then
     LOOP_DEV=$(losetup | grep "$IMG_NAME" | awk '{print $1}')
     if [ "$LOOP_DEV" == "" ]; then
-        echo "loop device not found!"
-        exit 1
+        error_msg "loop device not found!"
     fi
 else
-    echo "losetup $IMG_FILE failed!"
-    exit 1
+    error_msg "losetup $IMG_FILE failed!"
 fi
 
 # fix loopdev issue in kernel 5.19
@@ -369,8 +383,7 @@ for entry in $ENTRYS; do
     if [ $? -eq 0 ]; then
         echo "ok"
     else
-        echo "failed"
-        exit 1
+        error_msg "failed"
     fi
 done
 echo
@@ -421,7 +434,7 @@ config global
         option check_fs '0'
 
 config mount
-        option target '/overlay'
+        option target '/rom'
         option uuid '${NEW_ROOT_UUID}'
         option enabled '1'
         option enabled_fsck '1'
diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-update-amlogic b/luci-app-amlogic/root/usr/sbin/openwrt-update-amlogic
--- a/luci-app-amlogic/root/usr/sbin/openwrt-update-amlogic
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-update-amlogic
@@ -4,7 +4,7 @@
 # Copyright (C) 2020-- https://github.com/unifreq/openwrt_packit
 # Copyright (C) 2021-- https://github.com/ophub/luci-app-amlogic
 #======================================================================================
-
+#
 # The script supports directly setting parameters for update, skipping interactive selection
 # openwrt-update-amlogic ${OPENWRT_FILE} ${AUTO_MAINLINE_UBOOT} ${RESTORE_CONFIG}
 # E.g: openwrt-update-amlogic openwrt_s905d.img.gz yes restore
@@ -12,6 +12,42 @@
 
 # You can also execute the script directly, and interactively select related functions
 # E.g: openwrt-update-amlogic
+#
+#======================================================================================
+
+# Encountered a serious error, abort the script execution
+error_msg() {
+    echo -e "[ERROR] ${1}"
+    exit 1
+}
+
+# Get the partition name of the root file system
+get_root_partition_name() {
+    local paths=("/" "/overlay" "/rom")
+    local partition_name
+
+    for path in "${paths[@]}"; do
+        partition_name=$(df "${path}" | awk 'NR==2 {print $1}' | awk -F '/' '{print $3}')
+        [[ -n "${partition_name}" ]] && break
+    done
+
+    [[ -z "${partition_name}" ]] && error_msg "Cannot find the root partition!"
+    echo "${partition_name}"
+}
+
+# Get the partition message of the root file system
+get_root_partition_msg() {
+    local paths=("/" "/overlay" "/rom")
+    local partition_name
+
+    for path in "${paths[@]}"; do
+        partition_msg=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ "^" "'"${path}"'" "$" {print $0}')
+        [[ -n "${partition_msg}" ]] && break
+    done
+
+    [[ -z "${partition_msg}" ]] && error_msg "Cannot find the root partition message!"
+    echo "${partition_msg}"
+}
 
 # Receive one-key command related parameters
 IMG_NAME="${1}"
@@ -21,25 +57,16 @@ BACKUP_RESTORE_CONFIG="${3}"
 # Current device model
 MYDEVICE_NAME=$(cat /proc/device-tree/model | tr -d '\000')
 if [[ -z "${MYDEVICE_NAME}" ]]; then
-    echo "The device name is empty and cannot be recognized."
-    exit 1
+    error_msg "The device name is empty and cannot be recognized."
 elif [[ ! -f "/etc/flippy-openwrt-release" ]]; then
-    echo "The [ /etc/flippy-openwrt-release ] file is missing."
-    exit 1
+    error_msg "The [ /etc/flippy-openwrt-release ] file is missing."
 else
     echo -e "Current device: ${MYDEVICE_NAME} [ amlogic ]"
     sleep 3
 fi
 
 # Find the partition where root is located
-ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [[ -z "${ROOT_PTNAME}" ]]; then
-    ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
-    if [[ -z "${ROOT_PTNAME}" ]]; then
-        echo "Cannot find the partition corresponding to the root file system!"
-        exit 1
-    fi
-fi
+ROOT_PTNAME="$(get_root_partition_name)"
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
 case ${ROOT_PTNAME} in
@@ -60,8 +87,7 @@ mmcblk?p[1-4])
     LB_PRE="${ROOT_DISK_TYPE}_"
     ;;
 *)
-    echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-    exit 1
+    error_msg "Unable to recognize the disk type of ${ROOT_PTNAME}!"
     ;;
 esac
 
@@ -107,8 +133,7 @@ sync
 
 # check file
 if [ ! -f "${IMG_NAME}" ]; then
-    echo "No update file found."
-    exit 1
+    error_msg "No update file found."
 else
     echo "Start update from [ ${IMG_NAME} ]"
 fi
@@ -119,8 +144,7 @@ echo "Check the necessary dependencies..."
 for dep in ${DEPENDS}; do
     WITCH=$(busybox which ${dep})
     if [ "${WITCH}" == "" ]; then
-        echo "Dependent command: ${dep} does not exist, upgrade cannot be performed, only flash through U disk/TF card!"
-        exit 1
+        error_msg "Dependent command: ${dep} does not exist, upgrade cannot be performed, only flash through U disk/TF card!"
     else
         echo "${dep} path: ${WITCH}"
     fi
@@ -130,8 +154,7 @@ echo "Check passed"
 # find boot partition
 BOOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/boot$/ {print $0}')
 if [ "${BOOT_PART_MSG}" == "" ]; then
-    echo "Boot The partition does not exist, so the update cannot be continued!"
-    exit 1
+    error_msg "Boot The partition does not exist, so the update cannot be continued!"
 fi
 BOOT_NAME=$(echo ${BOOT_PART_MSG} | awk '{print $1}')
 BOOT_PATH=$(echo ${BOOT_PART_MSG} | awk '{print $2}')
@@ -153,10 +176,7 @@ n* | N*)
 esac
 
 # find root partition
-ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/$/ {print $0}')
-if [[ -z "${ROOT_PART_MSG}" ]]; then
-    ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/overlay$/ {print $0}')
-fi
+ROOT_PART_MSG="$(get_root_partition_msg)"
 ROOT_NAME=$(echo ${ROOT_PART_MSG} | awk '{print $1}')
 ROOT_PATH=$(echo ${ROOT_PART_MSG} | awk '{print $2}')
 ROOT_UUID=$(echo ${ROOT_PART_MSG} | awk '{print $4}')
@@ -171,8 +191,7 @@ ${EMMC_NAME}${PARTITION_NAME}3)
     NEW_ROOT_LABEL="${LB_PRE}ROOTFS1"
     ;;
 *)
-    echo "ROOTFS The partition location is incorrect, so the update cannot continue!"
-    exit 1
+    error_msg "ROOTFS The partition location is incorrect, so the update cannot continue!"
     ;;
 esac
 echo "NEW_ROOT_NAME: [ ${NEW_ROOT_NAME} ]"
@@ -180,8 +199,7 @@ echo "NEW_ROOT_NAME: [ ${NEW_ROOT_NAME} ]"
 # find new root partition
 NEW_ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | grep "${NEW_ROOT_NAME}" | awk '$3 ~ /^part$/ && $5 !~ /^\/$/ && $5 !~ /^\/boot$/ {print $0}')
 if [ "${NEW_ROOT_PART_MSG}" == "" ]; then
-    echo "The new ROOTFS partition does not exist, so the update cannot continue!"
-    exit 1
+    error_msg "The new ROOTFS partition does not exist, so the update cannot continue!"
 fi
 NEW_ROOT_NAME=$(echo ${NEW_ROOT_PART_MSG} | awk '{print $1}')
 NEW_ROOT_PATH=$(echo ${NEW_ROOT_PART_MSG} | awk '{print $2}')
@@ -202,12 +220,10 @@ losetup -f -P ${IMG_NAME}
 if [ ${?} -eq 0 ]; then
     LOOP_DEV=$(losetup | grep "${IMG_NAME}" | awk '{print $1}')
     if [ "${LOOP_DEV}" == "" ]; then
-        echo "loop device not found!"
-        exit 1
+        error_msg "loop device not found!"
     fi
 else
-    echo "losetup [ ${IMG_FILE} ] failed!"
-    exit 1
+    error_msg "losetup [ ${IMG_FILE} ] failed!"
 fi
 
 # fix loopdev issue in kernel 5.19
@@ -403,13 +419,11 @@ function check_and_fix_partition() {
     echo "Unsafe partition found, repairing ... "
     parted /dev/${target_dev_name} rm ${target_pt_idx} ||
         (
-            echo "rm partion ${target_pt_idx} failed"
-            exit 1
+            error_msg "rm partion ${target_pt_idx} failed"
         )
     parted /dev/${target_dev_name} mkpart primary btrfs "${safe_pt_begin_byte}b" "${cur_pt_end_byte}b" ||
         (
-            echo "create new partion ${target_pt_idx} failed"
-            exit 1
+            error_msg "create new partion ${target_pt_idx} failed"
         )
     echo "Partition repaired"
 }
@@ -462,8 +476,7 @@ for entry in ${ENTRYS}; do
     echo "Remove old [ ${entry} ] ... "
     rm -rf ${entry}
     if [[ "${?}" -ne "0" ]]; then
-        echo "failed."
-        exit 1
+        error_msg "failed."
     fi
 done
 
@@ -518,7 +531,7 @@ config  global
         option check_fs '0'
 
 config  mount
-        option target '/overlay'
+        option target '/rom'
         option uuid '${NEW_ROOT_UUID}'
         option enabled '1'
         option enabled_fsck '1'
@@ -719,32 +732,6 @@ btrfs subvolume snapshot -r etc .snapshots/etc-001
 
 cd ${WORK_DIR}
 
-#echo -n "umount /boot ... "
-#umount -f /boot
-#if [ $? -ne 0 ];then
-#    echo "failed! "
-#    umount ${P1}
-#    umount ${P2}
-#    losetup -D
-#    exit 1
-#else
-#    echo "ok"
-#fi
-#
-#echo "reformat ${BOOT_PATH} ..."
-#if mkfs.fat -n "${LB_PRE}BOOT" -F 32 ${BOOT_PATH} 2>/dev/null;then
-#    echo -n "mount /boot ..."
-#    mount -t vfat -o "errors=remount-ro" ${BOOT_PATH} /boot
-#    if [ $? -eq 0 ];then
-#        echo "ok"
-#    else
-#        echo "mount failed! The system has been destroyed and must be refreshed!"
-#	exit 1
-#    fi
-#else
-#    echo "format failed! The system has been destroyed and must be refreshed!"
-#    exit 1
-#fi
 echo "Change the label of ${BOOT_PATH} ... "
 fatlabel ${BOOT_PATH} "${LB_PRE}BOOT"
 echo "Start copying data， from [ ${P1} ] to [ /boot ] ..."
@@ -771,7 +758,7 @@ if [ -f ${P1}/uInitrd ]; then
             continue
         fi
     done
-    [ "${i}" -eq "10" ] && echo "uInitrd file copy failed." && exit 1
+    [ "${i}" -eq "10" ] && error_msg "uInitrd file copy failed."
 else
     echo "uInitrd file is missing."
 fi
@@ -791,10 +778,9 @@ if [ -f ${P1}/zImage ]; then
             continue
         fi
     done
-    [ "${i}" -eq "10" ] && echo "zImage file copy failed." && exit 1
+    [ "${i}" -eq "10" ] && error_msg "zImage file copy failed."
 else
-    echo "zImage file is missing."
-    exit 1
+    error_msg "zImage file is missing."
 fi
 
 if [ ${ROOT_DISK_TYPE} == "EMMC" ]; then
diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-update-kvm b/luci-app-amlogic/root/usr/sbin/openwrt-update-kvm
--- a/luci-app-amlogic/root/usr/sbin/openwrt-update-kvm
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-update-kvm
@@ -4,7 +4,7 @@
 # Copyright (C) 2022-- https://github.com/unifreq/openwrt_packit
 # Copyright (C) 2022-- https://github.com/ophub
 #======================================================================================
-
+#
 # The script supports directly setting parameters for update, skipping interactive selection
 # openwrt-update-amlogic ${OPENWRT_FILE} ${AUTO_MAINLINE_UBOOT} ${RESTORE_CONFIG} ${WORK_DIR}
 # E.g: openwrt-update-kvm openwrt_qemu-aarch64.img.gz no restore /mnt/vda4
@@ -12,6 +12,42 @@
 
 # You can also execute the script directly, and interactively select related functions
 # E.g: openwrt-update-kvm
+#
+#======================================================================================
+
+# Encountered a serious error, abort the script execution
+error_msg() {
+    echo -e "[ERROR] ${1}"
+    exit 1
+}
+
+# Get the partition name of the root file system
+get_root_partition_name() {
+    local paths=("/" "/overlay" "/rom")
+    local partition_name
+
+    for path in "${paths[@]}"; do
+        partition_name=$(df "${path}" | awk 'NR==2 {print $1}' | awk -F '/' '{print $3}')
+        [[ -n "${partition_name}" ]] && break
+    done
+
+    [[ -z "${partition_name}" ]] && error_msg "Cannot find the root partition!"
+    echo "${partition_name}"
+}
+
+# Get the partition message of the root file system
+get_root_partition_msg() {
+    local paths=("/" "/overlay" "/rom")
+    local partition_name
+
+    for path in "${paths[@]}"; do
+        partition_msg=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ "^" "'"${path}"'" "$" {print $0}')
+        [[ -n "${partition_msg}" ]] && break
+    done
+
+    [[ -z "${partition_msg}" ]] && error_msg "Cannot find the root partition message!"
+    echo "${partition_msg}"
+}
 
 # Receive one-key command related parameters
 IMG_NAME="${1}"
@@ -25,8 +61,7 @@ echo "Check the necessary dependencies..."
 for dep in ${DEPENDS}; do
     WITCH=$(busybox which ${dep})
     if [ "${WITCH}" == "" ]; then
-        echo "Dependent command: ${dep} does not exist, upgrade cannot be performed!"
-        exit 1
+        error_msg "Dependent command: ${dep} does not exist, upgrade cannot be performed!"
     else
         echo "${dep} path: ${WITCH}"
     fi
@@ -36,11 +71,9 @@ echo "Check passed"
 # Current device model
 source /etc/flippy-openwrt-release
 if [[ -z "${PLATFORM}" ]]; then
-    echo "The platform is empty."
-    exit 1
+    error_msg "The platform is empty."
 elif [[ "${PLATFORM}" != "qemu-aarch64" ]]; then
-    echo "The platform is missing, only support qemu-aarch64."
-    exit 1
+    error_msg "The platform is missing, only support qemu-aarch64."
 else
     echo -e "Current platform: [ ${PLATFORM} ]"
     sleep 3
@@ -48,14 +81,7 @@ fi
 
 # Find the partition where root is located
 # vda2 or vda3
-ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [[ -z "${ROOT_PTNAME}" ]]; then
-    ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
-    if [[ -z "${ROOT_PTNAME}" ]]; then
-        echo "Cannot find the partition corresponding to the root file system!"
-        exit 1
-    fi
-fi
+ROOT_PTNAME="$(get_root_partition_name)"
 
 # Find the disk where the partition is located, only supports sd?? hd?? vd??
 case ${ROOT_PTNAME} in
@@ -65,8 +91,7 @@ case ${ROOT_PTNAME} in
     LABEL_PRESTR=""
     ;;
 *)
-    echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-    exit 1
+    error_msg "Unable to recognize the disk type of ${ROOT_PTNAME}!"
     ;;
 esac
 
@@ -86,16 +111,14 @@ if [[ -z "${WORK_DIR}" ]]; then
     WORK_DIR="/mnt/${DISK_NAME}${PART_PRESTR}4/"
 fi
 if [[ ! -d "${WORK_DIR}" ]]; then
-    echo "the work directory is not exists. [ ${WORK_DIR} ]"
-    exit 1
+    error_msg "the work directory is not exists. [ ${WORK_DIR} ]"
 fi
 
 cd "${WORK_DIR}"
 if [[ -d "/tmp/upload" ]] && [[ -f "/tmp/upload/*img*" ]]; then
     mv -f /tmp/upload/*img* .
     if [[ $? -ne 0 ]]; then
-        echo "move file failed."
-        exit 1
+        error_msg "move file failed."
     fi
 fi
 sync
@@ -138,8 +161,7 @@ sync
 
 # check file
 if [ ! -f "${IMG_NAME}" ]; then
-    echo "No update file found."
-    exit 1
+    error_msg "No update file found."
 else
     echo "Start update from [ ${IMG_NAME} ]"
 fi
@@ -147,8 +169,7 @@ fi
 # find efi partition
 EFI_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/boot\/efi$/ {print $0}')
 if [ "${EFI_PART_MSG}" == "" ]; then
-    echo "The EFI partition does not exist, so the update cannot be continued!"
-    exit 1
+    error_msg "The EFI partition does not exist, so the update cannot be continued!"
 fi
 EFI_NAME=$(echo $EFI_PART_MSG | awk '{print $1}')
 EFI_DEV=$(echo $EFI_PART_MSG | awk '{print $2}')
@@ -168,10 +189,7 @@ else
 fi
 
 # find root partition
-ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/$/ {print $0}')
-if [[ -z "${ROOT_PART_MSG}" ]]; then
-    ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/overlay$/ {print $0}')
-fi
+ROOT_PART_MSG="$(get_root_partition_msg)"
 ROOT_NAME=$(echo ${ROOT_PART_MSG} | awk '{print $1}')
 ROOT_DEV=$(echo ${ROOT_PART_MSG} | awk '{print $2}')
 ROOT_UUID=$(echo ${ROOT_PART_MSG} | awk '{print $4}')
@@ -186,8 +204,7 @@ ${DISK_NAME}${PART_PRESTR}3)
     NEW_ROOT_LABEL="${LABEL_PRESTR}ROOTFS1"
     ;;
 *)
-    echo "ROOTFS The partition location is incorrect, so the update cannot continue!"
-    exit 1
+    error_msg "ROOTFS The partition location is incorrect, so the update cannot continue!"
     ;;
 esac
 echo "NEW_ROOT_NAME: [ ${NEW_ROOT_NAME} ]"
@@ -195,8 +212,7 @@ echo "NEW_ROOT_NAME: [ ${NEW_ROOT_NAME} ]"
 # find new root partition
 NEW_ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | grep "${NEW_ROOT_NAME}" | awk '$3 ~ /^part$/ && $5 !~ /^\/$/ && $5 !~ /^\/boot$/ {print $0}')
 if [ "${NEW_ROOT_PART_MSG}" == "" ]; then
-    echo "The new ROOTFS partition does not exist, so the update cannot continue!"
-    exit 1
+    error_msg "The new ROOTFS partition does not exist, so the update cannot continue!"
 fi
 NEW_ROOT_NAME=$(echo $NEW_ROOT_PART_MSG | awk '{print $1}')
 NEW_ROOT_DEV=$(echo $NEW_ROOT_PART_MSG | awk '{print $2}')
@@ -209,12 +225,10 @@ losetup -f -P $IMG_NAME
 if [ $? -eq 0 ]; then
     LOOP_DEV=$(losetup | grep "$IMG_NAME" | awk '{print $1}')
     if [ "$LOOP_DEV" == "" ]; then
-        echo "loop device not found!"
-        exit 1
+        error_msg "loop device not found!"
     fi
 else
-    echo "losetup [ $IMG_FILE ] failed!"
-    exit 1
+    error_msg "losetup [ $IMG_FILE ] failed!"
 fi
 
 # fix loopdev issue in kernel 5.19
@@ -381,8 +395,7 @@ for entry in $ENTRYS; do
     echo "Remove old [ $entry ] ... "
     rm -rf $entry
     if [ $? -ne 0 ]; then
-        echo "failed."
-        exit 1
+        error_msg "failed."
     fi
 done
 
@@ -437,7 +450,7 @@ config  global
         option check_fs '0'
 
 config  mount
-        option target '/overlay'
+        option target '/rom'
         option uuid '${NEW_ROOT_UUID}'
         option enabled '1'
         option enabled_fsck '1'
diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-update-rockchip b/luci-app-amlogic/root/usr/sbin/openwrt-update-rockchip
--- a/luci-app-amlogic/root/usr/sbin/openwrt-update-rockchip
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-update-rockchip
@@ -4,7 +4,7 @@
 # Copyright (C) 2020-- https://github.com/unifreq/openwrt_packit
 # Copyright (C) 2021-- https://github.com/ophub/luci-app-amlogic
 #======================================================================================
-
+#
 # The script supports directly setting parameters for update, skipping interactive selection
 # openwrt-update-rockchip ${OPENWRT_FILE} ${AUTO_MAINLINE_UBOOT} ${RESTORE_CONFIG}
 # E.g: openwrt-update-rockchip openwrt_s905d.img.gz yes restore
@@ -12,6 +12,42 @@
 
 # You can also execute the script directly, and interactively select related functions
 # E.g: openwrt-update-rockchip
+#
+#======================================================================================
+
+# Encountered a serious error, abort the script execution
+error_msg() {
+    echo -e "[ERROR] ${1}"
+    exit 1
+}
+
+# Get the partition name of the root file system
+get_root_partition_name() {
+    local paths=("/" "/overlay" "/rom")
+    local partition_name
+
+    for path in "${paths[@]}"; do
+        partition_name=$(df "${path}" | awk 'NR==2 {print $1}' | awk -F '/' '{print $3}')
+        [[ -n "${partition_name}" ]] && break
+    done
+
+    [[ -z "${partition_name}" ]] && error_msg "Cannot find the root partition!"
+    echo "${partition_name}"
+}
+
+# Get the partition message of the root file system
+get_root_partition_msg() {
+    local paths=("/" "/overlay" "/rom")
+    local partition_name
+
+    for path in "${paths[@]}"; do
+        partition_msg=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ "^" "'"${path}"'" "$" {print $0}')
+        [[ -n "${partition_msg}" ]] && break
+    done
+
+    [[ -z "${partition_msg}" ]] && error_msg "Cannot find the root partition message!"
+    echo "${partition_msg}"
+}
 
 # Receive one-key command related parameters
 IMG_NAME="${1}"
@@ -25,228 +61,218 @@ if [ -f /boot/armbianEnv.txt ]; then
 fi
 MYDEVICE_NAME=$(cat /proc/device-tree/model | tr -d '\000')
 case $MYDEVICE_NAME in
-	"")
-		echo "The device name is empty and cannot be recognized."
-			exit 1
-		;;
+"")
+    error_msg "The device name is empty and cannot be recognized."
+    ;;
 
-	"Chainedbox L1 Pro")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3328-l1pro-1296mhz.dtb"
-		fi
-		SOC="l1pro"
-		;;
-	"BeikeYun")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3328-beikeyun-1296mhz.dtb"
-		fi
-		SOC="beikeyun"
-		;;
-	"ZCuble1 Max")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3399-zcube1-max.dtb"
-		fi
-		SOC="zcube1 max"
-		;;
-	"JP TVbox 3566")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3566-jp-tvbox.dtb"
-		fi
-		SOC="jp-tvbox"
-		;;
-	"Radxa CM3 RPI CM4 IO")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3566-radxa-cm3-rpi-cm4-io.dtb"
-		fi
-		SOC="radxa-cm3-rpi-cm4-io"
-		;;
-	"FastRhino R66S"|"Lunzn FastRhino R66S")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3568-fastrhino-r66s.dtb"
-		fi
-		SOC="r66s"
-		;;
-	"FastRhino R68S"|"Lunzn FastRhino R68S")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3568-fastrhino-r68s.dtb"
-		fi
-		SOC="r68s"
-		;;
-	"RK3568 EC-X")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3568-ec-x.dtb"
-		fi
-		SOC="ec-x"
-		;;
-	"HINLINK OPC-H66K Board"|"Hlink H66K")
-		if [ -n "${CURRENT_FDTFILE}" ] && [ "${CURRENT_FDTFILE}" != "rk3568-opc-h66k.dtb" ];then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3568-hlink-h66k.dtb"
-		fi
-		SOC="h66k"
-		;;
-	"HINLINK OPC-H68K Board"|"Hlink H68K")
-		if [ -n "${CURRENT_FDTFILE}" ] && [ "${CURRENT_FDTFILE}" != "rk3568-opc-h68k.dtb" ];then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3568-hlink-h68k.dtb"
-		fi
-		SOC="h68k"
-		;;
-	"HINLINK OPC-H69K Board"|"Hlink H69K")
-		if [ -n "${CURRENT_FDTFILE}" ] && [ "${CURRENT_FDTFILE}" != "rk3568-opc-h69k.dtb" ];then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3568-hlink-h69k.dtb"
-		fi
-		SOC="h69k"
-		;;
-	"Radxa E25"|"Radxa E25 Carrier Board")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3568-radxa-e25.dtb"
-		fi
-		SOC="e25"
-		;;
-	"HINLINK OWL H88K-V3 Board"|"Hlink H88K-V3")
-		if [ -n "${CURRENT_FDTFILE}" ] && [ "${CURRENT_FDTFILE}" != "rk3568-hinlink-h88k-v3.dtb" ];then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3588-hlink-h88k-v3.dtb"
-		fi
-		SOC="h88k-v3"
-		;;
-	"HINLINK OWL H88K Board"|"Hlink H88K")
-		if [ -n "${CURRENT_FDTFILE}" ] && [ "${CURRENT_FDTFILE}" != "rk3568-hinlink-h88k.dtb" ];then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3588-hlink-h88k.dtb"
-		fi
-		SOC="ak88/h88k"
-		;;
-	"Hlink H28K")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3528-hlink-h28k.dtb"
-		fi
-		SOC="h28k"
-		;;
-	"Hlink HT2")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3528-hlink-ht2.dtb"
-		fi
-		SOC="ht2"
-		;;
-	"Radxa E20C")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3528-radxa-e20c.dtb"
-		fi
-		SOC="e20c"
-		;;
-	"Ariaboard Photonicat")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3568-photonicat.dtb"
-		fi
-		SOC="photonicat"
-		;;
-	"NLnet Watermelon Pi V3")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3568-watermelon-pi-v3.dtb"
-		fi
-		SOC="watermelon-pi-v3"
-		;;
-	"NLnet Watermelon Pi")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3568-watermelon-pi.dtb"
-		fi
-		SOC="watermelon-pi"
-		;;
-	"Radxa ROCK 5B"|"Radxa ROCK 5 Model B")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3588-rock-5b.dtb"
-		fi
-		SOC="rock5b"
-		;;
-	"Radxa ROCK 5C"|"Radxa ROCK 5 Model C")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3588s-rock-5c.dtb"
-		fi
-		SOC="rock5c"
-		;;
-	"Radxa E52C")
-		if [ -n "${CURRENT_FDTFILE}" ]; then
-			MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-		else
-			MYDTB_FDTFILE="rk3588s-radxa-e52c.dtb"
-		fi
-		SOC="e52c"
-		;;
-	*)	#default
-		if [ -f "/etc/flippy-openwrt-release" ]; then
-			source /etc/flippy-openwrt-release 2>/dev/null
-			if [ -n "${CURRENT_FDTFILE}" ]; then
-				MYDTB_FDTFILE="${CURRENT_FDTFILE}"
-			else
-				MYDTB_FDTFILE="${FDTFILE}"
-			fi
-			SOC="${SOC}"
-		else
-			echo "Unknown device: [ ${MYDEVICE_NAME} ], Not supported."
-			exit 1
-		fi
-		;;
+"Chainedbox L1 Pro")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3328-l1pro-1296mhz.dtb"
+    fi
+    SOC="l1pro"
+    ;;
+"BeikeYun")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3328-beikeyun-1296mhz.dtb"
+    fi
+    SOC="beikeyun"
+    ;;
+"ZCuble1 Max")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3399-zcube1-max.dtb"
+    fi
+    SOC="zcube1 max"
+    ;;
+"JP TVbox 3566")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3566-jp-tvbox.dtb"
+    fi
+    SOC="jp-tvbox"
+    ;;
+"Radxa CM3 RPI CM4 IO")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3566-radxa-cm3-rpi-cm4-io.dtb"
+    fi
+    SOC="radxa-cm3-rpi-cm4-io"
+    ;;
+"FastRhino R66S" | "Lunzn FastRhino R66S")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3568-fastrhino-r66s.dtb"
+    fi
+    SOC="r66s"
+    ;;
+"FastRhino R68S" | "Lunzn FastRhino R68S")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3568-fastrhino-r68s.dtb"
+    fi
+    SOC="r68s"
+    ;;
+"RK3568 EC-X")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3568-ec-x.dtb"
+    fi
+    SOC="ec-x"
+    ;;
+"HINLINK OPC-H66K Board" | "Hlink H66K")
+    if [ -n "${CURRENT_FDTFILE}" ] && [ "${CURRENT_FDTFILE}" != "rk3568-opc-h66k.dtb" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3568-hlink-h66k.dtb"
+    fi
+    SOC="h66k"
+    ;;
+"HINLINK OPC-H68K Board" | "Hlink H68K")
+    if [ -n "${CURRENT_FDTFILE}" ] && [ "${CURRENT_FDTFILE}" != "rk3568-opc-h68k.dtb" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3568-hlink-h68k.dtb"
+    fi
+    SOC="h68k"
+    ;;
+"HINLINK OPC-H69K Board" | "Hlink H69K")
+    if [ -n "${CURRENT_FDTFILE}" ] && [ "${CURRENT_FDTFILE}" != "rk3568-opc-h69k.dtb" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3568-hlink-h69k.dtb"
+    fi
+    SOC="h69k"
+    ;;
+"Radxa E25" | "Radxa E25 Carrier Board")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3568-radxa-e25.dtb"
+    fi
+    SOC="e25"
+    ;;
+"HINLINK OWL H88K-V3 Board" | "Hlink H88K-V3")
+    if [ -n "${CURRENT_FDTFILE}" ] && [ "${CURRENT_FDTFILE}" != "rk3568-hinlink-h88k-v3.dtb" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3588-hlink-h88k-v3.dtb"
+    fi
+    SOC="h88k-v3"
+    ;;
+"HINLINK OWL H88K Board" | "Hlink H88K")
+    if [ -n "${CURRENT_FDTFILE}" ] && [ "${CURRENT_FDTFILE}" != "rk3568-hinlink-h88k.dtb" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3588-hlink-h88k.dtb"
+    fi
+    SOC="ak88/h88k"
+    ;;
+"Hlink H28K")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3528-hlink-h28k.dtb"
+    fi
+    SOC="h28k"
+    ;;
+"Hlink HT2")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3528-hlink-ht2.dtb"
+    fi
+    SOC="ht2"
+    ;;
+"Radxa E20C")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3528-radxa-e20c.dtb"
+    fi
+    SOC="e20c"
+    ;;
+"Ariaboard Photonicat")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3568-photonicat.dtb"
+    fi
+    SOC="photonicat"
+    ;;
+"NLnet Watermelon Pi V3")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3568-watermelon-pi-v3.dtb"
+    fi
+    SOC="watermelon-pi-v3"
+    ;;
+"NLnet Watermelon Pi")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3568-watermelon-pi.dtb"
+    fi
+    SOC="watermelon-pi"
+    ;;
+"Radxa ROCK 5B" | "Radxa ROCK 5 Model B")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3588-rock-5b.dtb"
+    fi
+    SOC="rock5b"
+    ;;
+"Radxa ROCK 5C" | "Radxa ROCK 5 Model C")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3588s-rock-5c.dtb"
+    fi
+    SOC="rock5c"
+    ;;
+"Radxa E52C")
+    if [ -n "${CURRENT_FDTFILE}" ]; then
+        MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+    else
+        MYDTB_FDTFILE="rk3588s-radxa-e52c.dtb"
+    fi
+    SOC="e52c"
+    ;;
+*) #default
+    if [ -f "/etc/flippy-openwrt-release" ]; then
+        source /etc/flippy-openwrt-release 2>/dev/null
+        if [ -n "${CURRENT_FDTFILE}" ]; then
+            MYDTB_FDTFILE="${CURRENT_FDTFILE}"
+        else
+            MYDTB_FDTFILE="${FDTFILE}"
+        fi
+        SOC="${SOC}"
+    else
+        error_msg "Unknown device: [ ${MYDEVICE_NAME} ], Not supported."
+    fi
+    ;;
 esac
 
 [[ -z "${MYDTB_FDTFILE}" || -z "${SOC}" ]] && {
-    echo "Invalid FDTFILE or SOC: [ ${MYDTB_FDTFILE} / ${SOC} ]"
-    exit 1
+    error_msg "Invalid FDTFILE or SOC: [ ${MYDTB_FDTFILE} / ${SOC} ]"
 }
 
 echo -e "Current device: ${MYDEVICE_NAME} [ ${SOC} ]"
 sleep 3
 
 # Find the partition where root is located
-ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [[ -z "${ROOT_PTNAME}" ]]; then
-    ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
-    if [[ -z "${ROOT_PTNAME}" ]]; then
-        echo "Cannot find the partition corresponding to the root file system!"
-        exit 1
-    fi
-fi
+ROOT_PTNAME="$(get_root_partition_name)"
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
 case ${ROOT_PTNAME} in
@@ -266,8 +292,7 @@ nvme?n?p?)
     LB_PRE="USB_"
     ;;
 *)
-    echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-    exit 1
+    error_msg "Unable to recognize the disk type of ${ROOT_PTNAME}!"
     ;;
 esac
 
@@ -312,8 +337,7 @@ sync
 
 # check file
 if [ ! -f "${IMG_NAME}" ]; then
-    echo "No update file found."
-    exit 1
+    error_msg "No update file found."
 else
     echo "Start update from [ ${IMG_NAME} ]"
 fi
@@ -321,8 +345,7 @@ fi
 # find boot partition
 BOOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/boot$/ {print $0}')
 if [ "${BOOT_PART_MSG}" == "" ]; then
-    echo "The boot partition is not exists or not mounted, so it cannot be upgraded with this script!"
-    exit 1
+    error_msg "The boot partition is not exists or not mounted, so it cannot be upgraded with this script!"
 fi
 
 BR_FLAG=1
@@ -345,10 +368,7 @@ BOOT_PATH=$(echo ${BOOT_PART_MSG} | awk '{print $2}')
 BOOT_UUID=$(echo ${BOOT_PART_MSG} | awk '{print $4}')
 
 # find root partition
-ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/$/ {print $0}')
-if [[ -z "${ROOT_PART_MSG}" ]]; then
-    ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/overlay$/ {print $0}')
-fi
+ROOT_PART_MSG="$(get_root_partition_msg)"
 ROOT_NAME=$(echo ${ROOT_PART_MSG} | awk '{print $1}')
 ROOT_PATH=$(echo ${ROOT_PART_MSG} | awk '{print $2}')
 ROOT_UUID=$(echo ${ROOT_PART_MSG} | awk '{print $4}')
@@ -362,16 +382,14 @@ ${EMMC_NAME}${PARTITION_NAME}3)
     NEW_ROOT_LABEL="${LB_PRE}ROOTFS1"
     ;;
 *)
-    echo "The root partition location is invalid, so it cannot be upgraded with this script!"
-    exit 1
+    error_msg "The root partition location is invalid, so it cannot be upgraded with this script!"
     ;;
 esac
 
 # find new root partition
 NEW_ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | grep "${NEW_ROOT_NAME}" | awk '$3 ~ /^part$/ && $5 !~ /^\/$/ && $5 !~ /^\/boot$/ {print $0}')
 if [ "${NEW_ROOT_PART_MSG}" == "" ]; then
-    echo "The new root partition is not exists, so it cannot be upgraded with this script!"
-    exit 1
+    error_msg "The new root partition is not exists, so it cannot be upgraded with this script!"
 fi
 NEW_ROOT_NAME=$(echo ${NEW_ROOT_PART_MSG} | awk '{print $1}')
 NEW_ROOT_PATH=$(echo ${NEW_ROOT_PART_MSG} | awk '{print $2}')
@@ -383,12 +401,10 @@ losetup -f -P ${IMG_NAME}
 if [[ "${?}" -eq "0" ]]; then
     LOOP_DEV=$(losetup | grep "${IMG_NAME}" | awk '{print $1}')
     if [ "$LOOP_DEV" == "" ]; then
-        echo "loop device not found!"
-        exit 1
+        error_msg "loop device not found!"
     fi
 else
-    echo "losetup ${IMG_FILE} failed!"
-    exit 1
+    error_msg "losetup ${IMG_FILE} failed!"
 fi
 
 # fix loopdev issue in kernel 5.19
@@ -616,7 +632,7 @@ config global
         option check_fs '0'
 
 config mount
-        option target '/overlay'
+        option target '/rom'
         option uuid '${NEW_ROOT_UUID}'
         option enabled '1'
         option enabled_fsck '1'
@@ -782,13 +798,13 @@ echo
 
 echo -n "Update boot args ... "
 
-if [ -f /tmp/armbianEnv.txt ];then
+if [ -f /tmp/armbianEnv.txt ]; then
     ORIG_OVERLAYS=$(grep '^overlays=' /tmp/armbianEnv.txt)
     ORIG_USER_OVERLAYS=$(grep '^user_overlays=' /tmp/armbianEnv.txt)
     sed -e '/user_overlays=/d' -i armbianEnv.txt
     sed -e '/overlays=/d' -i armbianEnv.txt
-    echo "$ORIG_OVERLAYS" >> armbianEnv.txt
-    echo "$ORIG_USER_OVERLAYS" >> armbianEnv.txt
+    echo "$ORIG_OVERLAYS" >>armbianEnv.txt
+    echo "$ORIG_USER_OVERLAYS" >>armbianEnv.txt
 fi
 
 sed -e '/fdtfile=/d' -i armbianEnv.txt
@@ -797,11 +813,11 @@ sed -e '/rootfstype=/d' -i armbianEnv.txt
 sed -e '/rootflags=/d' -i armbianEnv.txt
 case $SOC in
 l1pro | beikeyun)
-	echo "fdtfile=/dtb/rockchip/${MYDTB_FDTFILE}" >>armbianEnv.txt
-	;;
+    echo "fdtfile=/dtb/rockchip/${MYDTB_FDTFILE}" >>armbianEnv.txt
+    ;;
 *)
-	echo "fdtfile=rockchip/${MYDTB_FDTFILE}" >>armbianEnv.txt
-	;;
+    echo "fdtfile=rockchip/${MYDTB_FDTFILE}" >>armbianEnv.txt
+    ;;
 esac
 cat >>armbianEnv.txt <<EOF
 rootdev=UUID=${NEW_ROOT_UUID}
@@ -810,9 +826,9 @@ rootflags=compress=zstd:${ZSTD_LEVEL}
 EOF
 
 # 如果新的dtb文件不存在,则用旧的代替
-if [ ! -f "dtb/rockchip/${MYDTB_FDTFILE}" ];then
-	echo "The new dtb file does not exist, replace it with the old one."
-	cp -v /tmp/${CURRENT_FDTFILE} dtb/rockchip/${MYDTB_FDTFILE}
+if [ ! -f "dtb/rockchip/${MYDTB_FDTFILE}" ]; then
+    echo "The new dtb file does not exist, replace it with the old one."
+    cp -v /tmp/${CURRENT_FDTFILE} dtb/rockchip/${MYDTB_FDTFILE}
 fi
 sync
 
